[brew]
name = "example"
version = "0.1.0"

[blends.junit]
author = "junit"
version = "4"

[blends.beans]
path = "../"
version = "*"

[blends.example]
version = "*"
url = "https://github.com/mendelsshop/barista"

