[brew]
name = "example"
version = "0.1.0"

[[bin]]
name = "AWK"
 
[blends.junit]
author = "junit"
version = "^4"

[blends.emoji-java]
author = "com.vdurmont"
version = "^5"

[blends.sushi]
author = "net.oneandone"
version = "*"

